### ISSUE TITLE
Golemschutzschild Trigger Reparatur

### ISSUE THREAD

**Issue by Timtam** [Timtam/Avalon#5]
Um die Komplikationen zu beheben, welche den Golemschutzschild-Zauber auslösen, wenn andere Leute einen Schild zaubern, ist entweder eine Meldungs-Änderung seitens Avalon nötig oder das Abfangen des Golemnamens beim Abholen/Wegbringen oder anderen Aktionen und anschließend das dynamische Erstellen von Triggern, spezifiziert auf die gewonnen Daten.

**Comment by Chiaray** [comment]
wurde bereits behoben (ist somit nicht mehr aktuell)
