### ISSUE TITLE
Dämonenkrieger-Integration

### ISSUE THREAD

**Issue by Timtam** [Timtam/Avalon#6]
Die Integration der Dämonenkrieger umfasst voraussichtlich folgende Punkte:
- vollkommene Sound-Ausstattung (eventuell nach und nach)
- Dämonennamen-Abkürzung (eventuelles Script, um nur noch beispielsweise 2 Buchstaben statt den ganzen Namen zu benötigen)

**Comment by Chiaray** [comment]
Bereits integriert
