### ISSUE TITLE
Fährtensuche-Formatierung

### ISSUE THREAD

**Issue by Timtam** [Timtam/Avalon#7]
Die Meistermeldung der Fährtensuche könnte effektiv geparst werden, um eine bessere Lesbarkeit, nicht nur für Blinde, zu gewehrleisten. Dwalin hat mit etwas ähnlichem bereits einmal angefangen und auch schon fast fertiggestellt, vielleicht könnte man dort einmal nachfragen?

**Comment by Chiaray** [comment]
Geplant ist bereits von mir ein kompletter Umbau der Ausgabemeldungen bei der Fährtensuche, um die Lesbarkeit für Sehende/Blinde zu erleichtern.

**Comment by Timtam** [comment]
sollte in Avalon selbst gelöst werden.
