### ISSUE TITLE
Farbliche Verschönerung für Sehende

### ISSUE THREAD

**Issue by Timtam** [Timtam/Avalon#8]
Die farbliche Hervorhebung wichtiger Meldungen für Sehende sollte zukünftig verstärkt integriert werden, um das Spielen mit Soundpack auch für Sehende angenehmer zu gestalten. Dazu müssen optimale Farbkombinationen (bisher RGB unterstützt) durch sehende zusammengestellt werden (einiges schon durch Dwalin getan, siehe Code avalon.xml etc), allerdings ist auch hier noch einige Arbeit nötig.

**Comment by Chiaray** [comment]
Da ist bereits viel schon geschehen denke ich. Falls jemand noch was zu Ergänzen hat, kann das Ticket gerne sonst nochmal aufmachen und konkrete Vorschläge hier notieren.
